// Generated by CoffeeScript 1.9.1
(function() {
  (function($) {
    return $.fn.extend({
      gphoto: function(options) {
        var provider, settings;
        settings = {
          provider: {
            name: 'fotorama'
          }
        };
        settings = $.extend(settings, options);
        provider = {
          fotorama: {
            map: function(imageUrl, image) {
              return {
                img: imageUrl + "w0/",
                thumb: imageUrl + "w64-h64/"
              };
            },
            insert: function($link, images) {
              var $fotorama;
              $fotorama = $('<div class="fotorama"></div>');
              $link.replaceWith($fotorama);
              $fotorama.fotorama($.extend({
                data: images
              }, settings.provider));
            }
          },
          ggrid: {
            map: function(imageUrl, image) {
              return {
                imageUrl: imageUrl,
                data: image
              };
            },
            insert: function($link, images) {
              var $ggrid;
              $ggrid = $('<div class="ggrid"></div>');
              options = {
                data: images
              };
              if ($link.attr("title") != null) {
                options['template'] = $link.attr("title");
              }
              $link.replaceWith($ggrid);
              $ggrid.ggrid($.extend(options, settings.provider));
              $ggrid.find('a').fluidbox();
            }
          }
        };
        return this.filter("[href ^= https\\:\\/\\/plus\\.google\\.com\\/photos]").each(function() {
          var $link, albumId, url, userId;
          $link = $(this);
          url = $.url($link.attr('href'));
          userId = url.segment(2);
          albumId = url.segment(4);
          return $.getJSON("https://picasaweb.google.com/data/feed/api/user/" + userId + "/albumid/" + albumId + "?kind=photo&access=public&alt=json-in-script&callback=?", function(data, status) {
            var images;
            images = data.feed.entry.map(function(image) {
              var $url, imageUrl;
              $url = $.url(image.content.src);
              imageUrl = ($url.attr('protocol')) + "://" + ($url.attr('host')) + ($url.attr('directory'));
              return provider[settings.provider.name].map(imageUrl, image);
            });
            provider[settings.provider.name].insert($link, images);
          });
        });
      }
    });
  })(jQuery);

}).call(this);

//# sourceMappingURL=jquery.gphoto.js.map
